grid:
  center_x: 22.014
  center_y: 0.253
  center_z: 52.794
  size_x: 22.0
  size_y: 22.0
  size_z: 22.0
docking:
  exhaustiveness: 32
  num_modes: 9
  energy_range: 3.0
  seed: 42
receptors:
  wildtype: data/raw/1M17.cif
  t790m: data/raw/2ITW.cif
ligands:
- gefitinib
- erlotinib
- afatinib
- dacomitinib
- osimertinib
