docking:
  exhaustiveness: 16
  num_modes: 9
  energy_range: 3.0
  seed: 42
grid:
  size_x: 22.0
  size_y: 22.0
  size_z: 22.0
receptors:
  wildtype:
    raw_path: data/raw/receptors/1M17.cif
    prepared_path: data/processed/receptors/1M17_prepared.pdbqt
    center_x: 23.57
    center_y: 9.772
    center_z: 59.367
  t790m:
    raw_path: data/raw/receptors/2JIT.cif
    prepared_path: data/processed/receptors/2JIT_prepared.pdbqt
    center_x: -12.458
    center_y: 29.144
    center_z: 36.837
ligands:
- gefitinib
- erlotinib
- afatinib
- dacomitinib
- osimertinib
